---
kind: pipeline
name: build-image
type: kubernetes

steps:
- name: build-image
  image: plugins/kaniko
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: docker.io/lib42/fpm
    dockerfile: Dockerfile
    tags:
      - latest
